config/routes.rb
Rails.application.routes.draw do
  # root path
  root "home#index"

  # home routes
  get "/home/index",         to: "home#index"
  get "/category/:category", to: "home#index", as: "home"

  # user routes
  get "cart/:id",           to: "user#cart",      as: "user_cart"
  get "history/:id",        to: "user#history",   as: "user_history"
  get "user/insertion/:id", to: "user#insertion", as: "user_insertion"
  get "profile/:id",        to: "user#profile",   as: "user_profile"
  get "wishlist/:id",       to: "user#wishlist",  as: "user_wishlist"

  # user API routes
  post "/update_user/:id",               to: "api/api#user_to_seller",     as: "update_user"
  post "/restore_user/:id",              to: "api/api#seller_to_user",     as: "restore_user"

  post "/cart/add/:insertion",           to: "api/api#add_to_cart",        as: "add_cart"
  post "/wishlist/add/:insertion",       to: "api/api#add_to_wishlist",    as: "add_wishlist"

  delete "/cart/remove/:insertion",      to: "api/api#remove_to_cart",     as: "remove_cart"
  delete "/wishlist/remove/:insertion",  to: "api/api#remove_to_wishlist", as: "remove_wishlist"
  
  # insertion routes
  get "/insertion/search",  to: "insertion#search",   as: "search_insertion"
  get "/insertion/:id",     to: "insertion#show",     as: "show_insertion"

  post "/insertion",        to: "insertion#create"
  post "/insertion/:id",    to: "insertion#edit",     as: "edit_insertion"

  delete "/insertion/:id",  to: "insertion#destroy",  as: "destroy_insertion"

  get "/meeting/new/:id", to: "meeting#new", as: "meeting"
  get "/meeting/:id", to: "meeting#show", as: "show_meeting"
  post "/meeting/accept/:id", to: "meeting#accept", as: "accept_meeting"
  post "/meeting", to: "meeting#create", as: "create_meeting"
  post "/meeting/:id", to: "meeting#update", as: "edit_meeting"
  delete "/meeting/:id", to: "meeting#destroy", as: "destroy_meeting"
  
  post "/review/create", to: "review#create", as: "create_review"

  post "questions/reply/:id", to: "questions#reply", as: "question_reply"
  post "/questions", to: "questions#create"

  post "/history/insertion/:id", to: "history#complete", as: "complete_purchase"
  
  resources :questions

  # devise routes
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :insertion
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :insertion
  belongs_to :seller
  belongs_to :user

  has_one_attached :image

  validates :date, presence: true
  validates :place, presence: true
end

app/models/insertion.rb
class Insertion < ApplicationRecord
  enum :categories, {
    accessories: 0,
    beauty: 1,
    books: 2,
    eletronics: 3,
    films: 4,
    games: 5,
    healts: 6,
    musics: 7,
    photos: 8,
    sports: 9,
    videogames: 10
  },
  prefix: true

  belongs_to :seller
  has_many :question
  has_many :history

  has_one_attached :image

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }

  def seller_location
    User.find(seller_id).location
  end

  def map 
    response = HTTP.get("https://maps.googleapis.com/maps/api/staticmap?center=40.714728,-73.998672&zoom=12&size=400x400&maptype=roadmap&key=AIzaSyABJc3-uSJdVUa1YJbAua2NRnqZx3UxnlI&signature=YOUR_SIGNATURE")
    response.parse
  end 

  private

  def self.seller_name(id)
    user = User.find(Seller.find(id).user_id)
    "#{user.first_name} #{user.last_name}"
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :insertion
  belongs_to :seller
  belongs_to :user

  validates :date, presence: true
  validates :place, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :insertion
  belongs_to :user

  validates :question, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :seller

  validates :rating, presence: true, numericality: { in: 1..5 }
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :user
  has_many :insertion, dependent: :destroy
  has_many :meeting, dependent: :destroy
  has_many :review
  has_many :history

  private

  def self.average_rating(id)
    Review.group(:seller_id).average(:rating)[id].to_i
  end
  
  def self.total_reviews(id)
    Review.group(:seller_id).count[id]
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_one :seller, dependent: :destroy
  has_many :cart
  has_many :meeting
  has_many :review
  has_many :wishlist
  has_many :question
  has_many :history

  geocoded_by :geocoding_address
  after_validation :geocode

  def geocoding_address
    [city, zip_code].join(", ")
  end

  def location
    [latitude, longitude]
  end

  def distance_from(coordinates)
      return if location.include?(nil) || coordinates.include?(nil)
      Geocoder::Calculations.distance_between(location, coordinates, units: :km).to_i
  end

  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.avatar = auth.info.image
      parse_name(user, auth.info.name)
    end
  end

  private

  def self.full_name(id)
    user = User.find(id)
    "#{user.first_name} #{user.last_name}"
  end

  def self.parse_name(user, name)
    name_arr = name.split(" ")
    user.first_name = name_arr.first
    user.last_name = name_arr.last
  end
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  belongs_to :insertion
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # * DONE
  def index
    @insertions = Insertion.all
    @latest_insertions = Insertion.order(:timestamp).reverse.first(5)

    if user_signed_in?
      @seller = Seller.find_by(user_id: current_user)
      @cart = Cart.where(user_id: current_user)
      @wishlist = Wishlist.where(user_id: current_user)

      if @seller 
        @insertions = @insertions.filter { |insertion| insertion.seller_id != @seller.id }
        @latest_insertions = @latest_insertions.filter { |insertion| insertion.seller_id != @seller.id }
      end
    end

    @category = params[:category]
    @insertions = @insertions.filter { |insertion| insertion.categories == @category } if @category
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: %i[profile cart wishlist]

  # * DONE
  def profile
    @seller = Seller.find_by(user_id: @user)

    if user_signed_in?
      @cart = Cart.where(user_id: current_user)
      @wishlist = Wishlist.where(user_id: current_user)
    end
    
    if @seller
      @insertions = Insertion.where(seller_id: @seller).order(:timestamp).reverse.first(4)
      @sold_insertions = History.where(seller_id: @seller).order(:timestamp).reverse.first(4)
      @reviews = Review.where(seller_id: @seller).order(:timestamp).reverse.first(4)
    end
  end

  # * DONE
  def cart
    redirect_to root_path if !user_signed_in? || current_user.id != params[:id].to_i
    @seller = Seller.find_by(user_id: current_user)
    @cart = Cart.where(user_id: @user)
  end
  
  # * DONE
  def wishlist
    redirect_to root_path if !user_signed_in? || current_user.id != params[:id].to_i
    @seller = Seller.find_by(user_id: current_user)
    @wishlist = Wishlist.where(user_id: @user)
  end
  
  def history
    redirect_to root_path if !user_signed_in? || current_user.id != params[:id].to_i

    @seller = Seller.find_by(user_id: current_user)

    if user_signed_in?
      @cart = Cart.where(user_id: current_user)
      @wishlist = Wishlist.where(user_id: current_user)
    end

    @insertions = History.where(user_id: current_user)
  end

  def insertion
    seller = Seller.find_by(user_id: params[:id])
    @insertions = Insertion.where(seller_id: seller)
  end

  private 

  # * DONE
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/insertion_helper.rb
module InsertionHelper
end

app/helpers/meeting_helper.rb
module MeetingHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/shared/_edit.html.erb
<div class="modal fade" id="edit<%= insertion.id %>" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button class="btn-close m-0" data-bs-dismiss="modal" aria-label="Close"></button>
        <h5 class="modal-title mx-auto">
          <span class="fw-bold">Modifica annuncio</span>
        </h5>
      </div>
      <div class="modal-body py-4">
        <div class="mb-3">
          <h5 class="mb-0">Vendi su Commerce</h5>
        </div>
        <%= form_for(:insertion, url: edit_insertion_path(insertion.id), html: { class: "form" }) do |f| %>
          <%= f.hidden_field :seller_id, value: Seller.find_by(user_id: @user).id %>
          <div class="row mb-3">
            <div class="col-7">
              <div class="form-floating">
                <%= f.text_field :title, class: "form-control", placeholder: "title", value: insertion.title %>
                <%= f.label :title %>
              </div>
            </div>
            <div class="col-3">
              <%= f.select :categories, Insertion.categories, { selected: Insertion.categories[insertion.categories] }, class: "form-select h-100" %>
            </div>
            <div class="col-2">
              <div class="form-floating">
                <%= f.number_field :price, class: "form-control", placeholder: "price", value: insertion.price %>
                <%= f.label :price %>
              </div>
            </div>
          </div>
          <div class="form-floating mb-3">
            <%= f.text_area :description, class: "form-control", rows: "10", placeholder: "description", value: insertion.description %>
            <%= f.label :description %>
          </div>
          <%= f.submit "Modifica", class: "modal-btn p-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_insertion.html.erb
<%# * DONE %>
<div class="insertion_class" id="insertion_<%= insertion.id %>">
  <%= link_to show_insertion_path(insertion), id: "show_insertion" do %>
    <%# card %>
    <div class="card">
      <%= image_tag(insertion.image, class: "insertion-image") %>

      <%# card-body %>
      <div class="card-body">
        <div>
          <h6 class="fw-bold mb-0"><%= insertion.title %></h6>
          <span class="fw-bold"><%= sprintf('%.2f', insertion.price) %> €</span>
        </div>
        <div>
          <% seller = insertion.seller_id %>
          <%= link_to user_profile_path(Seller.find(seller).user_id), class: "me-auto" do %>
            <%= Insertion.seller_name(seller) %>
          <% end %>
          <% if Seller.average_rating(seller) == 0 %>
            <span class="fw-light">Nessuna recensione</span>
          <% else%>
            <span class="fw-bold">
              (<%= Seller.total_reviews(seller) %>) <%= Seller.average_rating(seller) %>
              <i class="fa-solid fa-star fa-2xs"></i>    
            </span>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <% if (distance = User.find(current_user.id).distance_from(User.find(Seller.find(insertion.seller_id).user_id).location)) %>
            <% if distance > 20 %>
              <span><%= distance %> kilometers away</span>      
            <% else %>
              <span>Near to you</span>
            <% end %>
          <% end %>
          <div class="card-interaction">
            <%# wishlist section %>
            <% if @wishlist&.find_by(insertion_id: insertion) %>
              <%= button_to remove_wishlist_path(insertion), method: :delete, id:"wishlist_button"+insertion.id.to_s do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="#fe385c" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                </svg>
              <% end %>
            <% else %>
              <%= button_to add_wishlist_path(insertion) do %>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                </svg>
              <% end %>
            <% end %>
            
            <%# cart section %>
            <% if @cart&.find_by(insertion_id: insertion) %>
              <%= button_to remove_cart_path(insertion), method: :delete, id: "remove_cart" do %>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd" />
                </svg>
              <% end %>
            <% else %>
              <%= button_to add_cart_path(insertion), id: "add_cart" do %>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd" />
                </svg>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

</div>

app/views/shared/_login.html.erb
<div class="modal fade" id="login" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <button class="btn-close m-0" data-bs-dismiss="modal" aria-label="Close"></button>
        <h5 class="modal-title mx-auto">
          <span class="fw-bold">Accedi</span>
        </h5>
      </div>
      <div class="modal-body py-4">
        <div class="mb-3">
          <h5 class="mb-0">Benvenuto su Commerce</h5>
        </div>
        <%= form_for(:user, url: session_path(:user), html: { class: "login-form needs-validation" }) do |f| %>
          <div class="form-floating">
            <%= f.email_field :email, class: "form-control", placeholder: "name@example.com" %>
            <%= f.label :email %>
          </div>
          <div class="form-floating mb-3">
            <%= f.password_field :password, class: "form-control", placeholder: "password" %>
            <%= f.label :password %>
          </div>
          <%= f.submit "Continua", class: "modal-btn p-2" %>
        <% end %>
        <div class="d-flex justify-content-center align-items-center my-2">
          <hr class="w-100 mx-3"/>
          <span>oppure</span>
          <hr class="w-100 mx-3"/>
        </div>
        <div class="d-flex justify-content-center flex-column">
          <%= button_to user_google_oauth2_omniauth_authorize_path, method: :post, data: { turbo: false }, class: "position-relative other-btn text-center w-100 p-2" do %>
            <div class="position-absolute top-50 start-25 translate-middle ms-3">
              <svg viewBox="0 0 24 24" style="height: 20px; width: 20px;" xmlns="http://www.w3.org/2000/svg">
                <g transform="matrix(1, 0, 0, 1, 27.009001, -39.238998)">
                  <path fill="#4285F4" d="M -3.264 51.509 C -3.264 50.719 -3.334 49.969 -3.454 49.239 L -14.754 49.239 L -14.754 53.749 L -8.284 53.749 C -8.574 55.229 -9.424 56.479 -10.684 57.329 L -10.684 60.329 L -6.824 60.329 C -4.564 58.239 -3.264 55.159 -3.264 51.509 Z"/>
                  <path fill="#34A853" d="M -14.754 63.239 C -11.514 63.239 -8.804 62.159 -6.824 60.329 L -10.684 57.329 C -11.764 58.049 -13.134 58.489 -14.754 58.489 C -17.884 58.489 -20.534 56.379 -21.484 53.529 L -25.464 53.529 L -25.464 56.619 C -23.494 60.539 -19.444 63.239 -14.754 63.239 Z"/>
                  <path fill="#FBBC05" d="M -21.484 53.529 C -21.734 52.809 -21.864 52.039 -21.864 51.239 C -21.864 50.439 -21.724 49.669 -21.484 48.949 L -21.484 45.859 L -25.464 45.859 C -26.284 47.479 -26.754 49.299 -26.754 51.239 C -26.754 53.179 -26.284 54.999 -25.464 56.619 L -21.484 53.529 Z"/>
                  <path fill="#EA4335" d="M -14.754 43.989 C -12.984 43.989 -11.404 44.599 -10.154 45.789 L -6.734 42.369 C -8.804 40.429 -11.514 39.239 -14.754 39.239 C -19.444 39.239 -23.494 41.939 -25.464 45.859 L -21.484 48.949 C -20.534 46.099 -17.884 43.989 -14.754 43.989 Z"/>
                </g>
              </svg>
            </div>
            <span class="fw-bold">Continua con Google</span>
          <% end %>
          <%= button_to user_facebook_omniauth_authorize_path, method: :post, data: { turbo: false }, class: "position-relative other-btn text-center w-100 p-2 my-2" do %>
            <div class="position-absolute top-50 start-25 translate-middle ms-3">
              <svg xmlns="http://www.w3.org/2000/svg" style="height: 30px; width: 30px;" viewBox="-204.79995 -341.33325 1774.9329 2047.9995">
                <path d="M1365.333 682.667C1365.333 305.64 1059.693 0 682.667 0 305.64 0 0 305.64 0 682.667c0 340.738 249.641 623.16 576 674.373V880H402.667V682.667H576v-150.4c0-171.094 101.917-265.6 257.853-265.6 74.69 0 152.814 13.333 152.814 13.333v168h-86.083c-84.804 0-111.25 52.623-111.25 106.61v128.057h189.333L948.4 880H789.333v477.04c326.359-51.213 576-333.635 576-674.373" fill="#1877f2"/>
                <path d="M948.4 880l30.267-197.333H789.333V554.609C789.333 500.623 815.78 448 900.584 448h86.083V280s-78.124-13.333-152.814-13.333c-155.936 0-257.853 94.506-257.853 265.6v150.4H402.667V880H576v477.04a687.805 687.805 0 00106.667 8.293c36.288 0 71.91-2.84 106.666-8.293V880H948.4" fill="#fff"/>
              </svg>
            </div>
            <span class="fw-bold">Continua con Facebook</span>
          <% end %>
          <button class="position-relative other-btn text-center bg-transparent p-2" data-bs-toggle="modal" data-bs-target="#registration">
            <div class="position-absolute top-50 start-25 translate-middle ms-3">
              <svg xmlns="http://www.w3.org/2000/svg" style="height: 20px; width: 20px;" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M14.243 5.757a6 6 0 10-.986 9.284 1 1 0 111.087 1.678A8 8 0 1118 10a3 3 0 01-4.8 2.401A4 4 0 1114 10a1 1 0 102 0c0-1.537-.586-3.07-1.757-4.243zM12 10a2 2 0 10-4 0 2 2 0 004 0z" clip-rule="evenodd" />
              </svg>
            </div>
            <span class="fw-bold">Continua con un indirizzo email</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<%# * DONE %>
<header class="container-fluid py-1">
  <nav class="navbar navbar-light p-0">
    <div class="container-fluid px-0">
      <%# navbar logo %>
      <%= link_to root_path, class: "navbar-brand m-0" do %>
        <div class="d-inline-flex align-items-center">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M10 2a4 4 0 00-4 4v1H5a1 1 0 00-.994.89l-1 9A1 1 0 004 18h12a1 1 0 00.994-1.11l-1-9A1 1 0 0015 7h-1V6a4 4 0 00-4-4zm2 5V6a2 2 0 10-4 0v1h4zm-6 3a1 1 0 112 0 1 1 0 01-2 0zm7-1a1 1 0 100 2 1 1 0 000-2z" clip-rule="evenodd" />
          </svg>
          <h4 class="m-0">eShop</h4>
        </div>
      <% end %>

      <%# navbar search %>
      <%= form_with url: search_insertion_path, method: :get, class:"search-form", id:"search" do |f| %>
        <%= f.text_field :search, placeholder: "Cerca" %>
        <%= button_tag id:"Submit" do %>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
          </svg>
        <% end %>
      <% end %>

      <%# navbar user section %>
      <div class="d-inline-flex align-items-center">
        <% if user_signed_in? %>          
          <div class="seller-btn mx-2">
            <% if @seller&.active %>
              <%= button_to restore_user_path(current_user), remote: true do %>
                <span class="fw-bold">Fai una pausa dalle vendite</span>
              <% end %>
            <% else %>
              <%= button_to update_user_path(current_user) do %>
                <span class="fw-bold">Diventa un venditore</span>
              <% end %>
            <% end %>
          </div>
        <% end %>
        <div class="dropdown-link p-1">
          <div class="dropdown">
            <a data-bs-toggle="dropdown">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z" clip-rule="evenodd" />
              </svg>
            </a>
            <div class="dropdown-menu dropdown-menu-end mt-3">
              <% if !user_signed_in? %>
                <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#sign_up">
                  <span class="fw-bold">Registrati</span>
                </button>
                <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#sign_in">
                  <span>Accedi</span>
                </button>
              <% else %>
                <%= link_to user_profile_path(current_user), class: "dropdown-item", name: "Profilo" do %>
                  <span class="fw-bold" name="Profilo">Profilo</span>
                <% end %>
                <%= link_to show_meeting_path(current_user), class: "dropdown-item" do %>
                  <span>Prenotazioni</span>
                <% end %>
                <%= link_to user_history_path(current_user), class: "dropdown-item" do %>
                  <span>Acquisti</span>
                <% end %>
                <%= link_to user_cart_path(current_user), class: "dropdown-item" do %>
                  <span>Carrello (<%= Cart.where(user_id: current_user).length %>)</span>
                <% end %>
                <%= link_to user_wishlist_path(current_user), class: "dropdown-item" do %>
                  <span>Preferiti (<%= Wishlist.where(user_id: current_user).length %>)</span>
                <% end %>
                <hr class="my-2"/>
                <%= link_to destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } do %>
                  <span>Esci</span>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>
<%= render "shared/categories", categories: Insertion.categories %>
<hr />

app/views/shared/toast/_complete_registration.html.erb
<% user = User.find(current_user.id) %>
<% if user.zip_code.empty? || user.city.empty? || user.address.empty? %>  
  <div class="toast show" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
      <span class="fw-bold">Completa la tua registrazione</span>
    </div>
    <div class="toast-body">
      <div class="mb-2">
        <span>Per sbloccare tutte le potenzialità del sito, aggiungi le ultime informazioni richieste!</span>
      </div>
      <%= link_to "Clicca qui", user_profile_path(user), style: "color: #fe385c" %>
    </div>
  </div>
<% end %>