config/routes.rb
Rails.application.routes.draw do
  # root path
  root "home#index"

  # home routes
  get "/home/index",         to: "home#index"
  get "/category/:category", to: "home#index", as: "home"

  # user routes
  get "cart/:id",           to: "user#cart",      as: "user_cart"
  get "history/:id",        to: "user#history",   as: "user_history"
  get "user/insertion/:id", to: "user#insertion", as: "user_insertion"
  get "profile/:id",        to: "user#profile",   as: "user_profile"
  get "wishlist/:id",       to: "user#wishlist",  as: "user_wishlist"

  # user API routes
  post "/update_user/:id",               to: "api/api#user_to_seller",     as: "update_user"
  post "/restore_user/:id",              to: "api/api#seller_to_user",     as: "restore_user"

  post "/cart/add/:insertion",           to: "api/api#add_to_cart",        as: "add_cart"
  post "/wishlist/add/:insertion",       to: "api/api#add_to_wishlist",    as: "add_wishlist"

  delete "/cart/remove/:insertion",      to: "api/api#remove_to_cart",     as: "remove_cart"
  delete "/wishlist/remove/:insertion",  to: "api/api#remove_to_wishlist", as: "remove_wishlist"
  
  # insertion routes
  get "/insertion/search",  to: "insertion#search",   as: "search_insertion"
  get "/insertion/:id",     to: "insertion#show",     as: "show_insertion"

  post "/insertion",        to: "insertion#create"
  post "/insertion/:id",    to: "insertion#edit",     as: "edit_insertion"

  delete "/insertion/:id",  to: "insertion#destroy",  as: "destroy_insertion"

  get "/meeting/new/:id", to: "meeting#new", as: "meeting"
  get "/meeting/:id", to: "meeting#show", as: "show_meeting"
  post "/meeting/accept/:id", to: "meeting#accept", as: "accept_meeting"
  post "/meeting", to: "meeting#create", as: "create_meeting"
  post "/meeting/:id", to: "meeting#update", as: "edit_meeting"
  delete "/meeting/:id", to: "meeting#destroy", as: "destroy_meeting"
  
  post "/review/create", to: "review#create", as: "create_review"

  post "questions/reply/:id", to: "questions#reply", as: "question_reply"
  post "/questions", to: "questions#create"

  post "/history/insertion/:id", to: "history#complete", as: "complete_purchase"
  
  resources :questions

  # devise routes
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_one :seller, dependent: :destroy
  has_many :cart
  has_many :meeting
  has_many :review
  has_many :wishlist
  has_many :question
  has_many :history

  geocoded_by :geocoding_address
  after_validation :geocode

  def geocoding_address
    [city, zip_code].join(", ")
  end

  def location
    [latitude, longitude]
  end

  def distance_from(coordinates)
      return if location.include?(nil) || coordinates.include?(nil)
      Geocoder::Calculations.distance_between(location, coordinates, units: :km).to_i
  end

  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.avatar = auth.info.image
      parse_name(user, auth.info.name)
    end
  end

  private

  def self.full_name(id)
    user = User.find(id)
    "#{user.first_name} #{user.last_name}"
  end

  def self.parse_name(user, name)
    name_arr = name.split(" ")
    user.first_name = name_arr.first
    user.last_name = name_arr.last
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: %i[profile cart wishlist]

  # * DONE
  def profile
    @seller = Seller.find_by(user_id: @user)

    if user_signed_in?
      @cart = Cart.where(user_id: current_user)
      @wishlist = Wishlist.where(user_id: current_user)
    end
    
    if @seller
      @insertions = Insertion.where(seller_id: @seller).order(:timestamp).reverse.first(4)
      @sold_insertions = History.where(seller_id: @seller).order(:timestamp).reverse.first(4)
      @reviews = Review.where(seller_id: @seller).order(:timestamp).reverse.first(4)
    end
  end

  # * DONE
  def cart
    redirect_to root_path if !user_signed_in? || current_user.id != params[:id].to_i
    @seller = Seller.find_by(user_id: current_user)
    @cart = Cart.where(user_id: @user)
  end
  
  # * DONE
  def wishlist
    redirect_to root_path if !user_signed_in? || current_user.id != params[:id].to_i
    @seller = Seller.find_by(user_id: current_user)
    @wishlist = Wishlist.where(user_id: @user)
  end
  
  def history
    redirect_to root_path if !user_signed_in? || current_user.id != params[:id].to_i

    @seller = Seller.find_by(user_id: current_user)

    if user_signed_in?
      @cart = Cart.where(user_id: current_user)
      @wishlist = Wishlist.where(user_id: current_user)
    end

    @insertions = History.where(user_id: current_user)
  end

  def insertion
    seller = Seller.find_by(user_id: params[:id])
    @insertions = Insertion.where(seller_id: seller)
  end

  private 

  # * DONE
  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(auth)
    if @user.present?
      sign_in_and_redirect @user, event: :authentication
    end
  end

  def google_oauth2
    @user = User.from_omniauth(auth)
    if @user.present?
      session[:access_token] = auth[:credentials][:token]
      sign_in_and_redirect @user, event: :authentication
    end
  end

  def failure
    redirect_to root_path
  end

  def auth
    @auth ||= request.env["omniauth.auth"]
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice,
                           :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource,
                     location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
    end
  end

  # PUT /resource
  def update
    user = User.find(params[:user][:user_id])
    if user.provider.in?(["google_oauth2", "facebook"])
      user.update_without_password(city: params[:user][:city], zip_code: params[:user][:zip_code], address: params[:user][:address])
    else
      user.update(account_update_params)
    end
    sign_in_and_redirect user
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up,keys: %i[first_name last_name city zip_code address])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name city zip_code address])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/cart.html.erb
<div class="my-3">
  <span class="fw-bold">Il tuo carrello</span>
  <% if @cart.length == 0 %>
    <h6 class="mt-3">Nessun elemento</h6>
  <% end %>
</div>
<div class="row row-cols-4">
  <% @cart.each do |insertion| %>
    <div class="col mb-4">
      <%= render "shared/insertion", insertion: Insertion.find(insertion.insertion_id) %>
    </div>
  <% end %>
</div>

app/views/user/history.html.erb
<div class="my-3">
  <span class="fw-bold">I tuoi acquisti</span>
  <% if @cart.length == 0 %>
    <h6 class="mt-3">Nessun elemento</h6>
  <% end %>
</div>
<div class="row row-cols-4">
  <% @insertions.each do |insertion| %>
    <div class="col mb-4">
      <div class="card">
        <%= image_tag(Insertion.find(insertion.id).image, class: "insertion-image") %>

        <%# card-body %>
        <div class="card-body">
          <div>
            <h6 class="fw-bold mb-0"><%= Insertion.find(insertion.id).title %></h6>
            <span class="fw-bold"><%= sprintf('%.2f', Insertion.find(insertion.id).price) %> €</span>
          </div>
          <div>
            <% seller = insertion.seller_id %>
            <%= link_to user_profile_path(Seller.find(seller).user_id), class: "me-auto" do %>
              <%= Insertion.seller_name(seller) %>
            <% end %>
            <% if Seller.average_rating(seller) == 0 %>
              <span class="fw-light">Nessuna recensione</span>
            <% else%>
              <span class="fw-bold">
                (<%= Seller.total_reviews(seller) %>) <%= Seller.average_rating(seller) %>
                <i class="fa-solid fa-star fa-2xs"></i>    
              </span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/user/insertion.html.erb
<div class="my-3">
  <span class="fw-bold">Annunci</span>
  <% if @insertions.length == 0 %>
    <h6 class="mt-3">Nessun elemento</h6>
  <% end %>
</div>
<div class="row row-cols-4">
  <% @insertions.each do |insertion| %>
    <div class="col mb-4">
      <%= render "shared/insertion", insertion: insertion %>
    </div>
  <% end %>
</div>

app/views/user/profile.html.erb
<%# * DONE %>
<div class="profile-container my-5">
  <%# profile container %>
  <% if @seller %>
    <div>
      <span>
        <% if !Seller.total_reviews(@seller.id) %>
          Nessuna valutazione disponibile
        <% else %>
          (<%= Seller.total_reviews(@seller.id) %>) <%= Seller.average_rating(@seller.id) %>
          <i class="fa-solid fa-star fa-2xs"></i>     
        <% end %>
      </span>
    </div>  
  <% end %>
  <div class="d-inline-flex align-items-center flex-column">
    <h6 class="fw-bold mb-0"><%= @user.first_name %> <%= @user.last_name %></h6>
    <% if !@user.zip_code.empty? && !@user.city.empty? && !@user.address.empty? %>
      <span class="mb-0"><%= @user.zip_code %>, <%= @user.address %>, <%= @user.city %></span>
    <% end %>
    <span><%= @user.email %></span>
    <% if user_signed_in? && current_user == @user %>        
      <button class="bg-transparent border-0" data-bs-toggle="modal" data-bs-target="#edit_registration">
        <span class="fw-bold" style="color: #fe385c">modifica</span>
      </button>
      <%= render "shared/modal/edit_user" %>
    <% end %>
  </div>

  <%# profile seller status %>
  <% if @seller %> 
    <% if !@seller.active %>
      <span class="btn btn-sm btn-danger fw-bold">inattivo</span>
    <% else %>
      <span class="btn btn-sm btn-success fw-bold">attivo</span>
    <% end %>
  <% end %>
</div>
<hr />

<%# seller section %>
<% if Seller.find_by(user_id: @user) %>
  <%# insertion section %>
  <div class="insertion-section my-3">
    <div class="d-flex justify-content-between align-items-center w-100">
      <div>
        <span class="fw-bold">Annunci</span>
        <% if user_signed_in? && current_user == @user %>
          <button data-bs-toggle="modal" data-bs-target="#insertion" id="aggiungi_elemento">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v2H7a1 1 0 100 2h2v2a1 1 0 102 0v-2h2a1 1 0 100-2h-2V7z" clip-rule="evenodd" />
            </svg>
          </button>
        <% end %>
      </div>
      <%= link_to "Visualizza annunci", user_insertion_path(@user), class: "fw-bold", style: "color: #fe385c; font-size: 12px;" %>
    </div>
  </div>
  <%= render "shared/modal/create" %>

  <%# seller's insertions %>
  <div class="row row-cols-4">
    <% @insertions.each do |insertion| %>
      <% if !insertion.sold %>          
        <div class="col mb-4">
          <% if user_signed_in? && current_user == @user %>              
            <div class="insertion-features">
              <%= button_to destroy_insertion_path(insertion), method: :delete do %>
                <span>Elimina</span>
              <% end %>
              <button data-bs-toggle="modal" data-bs-target="#edit<%= insertion.id %>">
                <span>Modifica</span>
              </button>
            </div>
            <%= render "shared/modal/edit_insertion", insertion: insertion %>
          <% end %>
          <%= render "shared/insertion", insertion: insertion %>
        </div>
      <% end %>
    <% end %>
  </div>

  <%# seller's reviews %>
  <div class="insertion-section mb-3">
    <span class="fw-bold">Recensioni</span>
    <% if user_signed_in? && current_user != @user %>
      <button class="border-0 bg-transparent" data-bs-toggle="modal" data-bs-target="#review" id="create_review">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v2H7a1 1 0 100 2h2v2a1 1 0 102 0v-2h2a1 1 0 100-2h-2V7z" clip-rule="evenodd" />
        </svg>
      </button>
    <% end %>
  </div>
  <%= render "shared/modal/review" %>

  <div class="row row-cols-4">
    <% @reviews.each do |review| %>
      <div class="col mb-4">
        <div class="review-container">
          <%= link_to user_profile_path(review.user_id) do %>
            <span class="fw-bold"><%= User.find(review.user_id).first_name %> <%= User.find(review.user_id).last_name %></span>
          <% end %>
          <div>
            <% (1..review.rating).each do %>
              <i class="fa-solid fa-star fa-2xs"></i>              
            <% end %>
            <% (review.rating..4).each do %>
              <i class="fa-regular fa-star fa-2xs"></i>              
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <%# seller's sold history %>
  <% if Seller.find_by(user_id: @user) %>
    <div class="insertion-section mb-3">
      <% if @sold_insertions.length > 0 %>
        <span class="fw-bold">Articoli venduti</span>
      <% end %>
    </div>
    <div class="row row-cols-4">
      <% @sold_insertions.each do |insertion| %>
        <div class="col mb-4">
          <div class="card">
            <%= image_tag(Insertion.find(insertion.id).image, class: "insertion-image") %>

            <%# card-body %>
            <div class="card-body">
              <div>
                <h6 class="fw-bold mb-0"><%= Insertion.find(insertion.id).title %></h6>
                <span class="fw-bold"><%= sprintf('%.2f', Insertion.find(insertion.id).price) %> €</span>
              </div>
              <div>
                <% seller = insertion.seller_id %>
                <%= link_to user_profile_path(Seller.find(seller).user_id), class: "me-auto" do %>
                  <%= Insertion.seller_name(seller) %>
                <% end %>
                <% if Seller.average_rating(seller) == 0 %>
                  <span class="fw-light">Nessuna recensione</span>
                <% else%>
                  <span class="fw-bold">
                    (<%= Seller.total_reviews(seller) %>) <%= Seller.average_rating(seller) %>
                    <i class="fa-solid fa-star fa-2xs"></i>    
                  </span>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/user/wishlist.html.erb
<div class="my-3">
  <span class="fw-bold">I tuoi preferiti</span>
  <% if @wishlist.length == 0 %>
    <h6 class="mt-3">Nessun elemento</h6>
  <% end %>
</div>
<div class="row row-cols-4">
  <% @wishlist.each do |insertion| %>
    <div class="col mb-4">
      <%= render "shared/insertion", insertion: Insertion.find(insertion.insertion_id) %>
    </div>
  <% end %>
</div>