config/routes.rb
Rails.application.routes.draw do
  # root path
  root "home#index"

  # home routes
  get "/home/index",         to: "home#index"
  get "/category/:category", to: "home#index", as: "home"

  # user routes
  get "cart/:id",           to: "user#cart",      as: "user_cart"
  get "history/:id",        to: "user#history",   as: "user_history"
  get "user/insertion/:id", to: "user#insertion", as: "user_insertion"
  get "profile/:id",        to: "user#profile",   as: "user_profile"
  get "wishlist/:id",       to: "user#wishlist",  as: "user_wishlist"

  # user API routes
  post "/update_user/:id",               to: "api/api#user_to_seller",     as: "update_user"
  post "/restore_user/:id",              to: "api/api#seller_to_user",     as: "restore_user"

  post "/cart/add/:insertion",           to: "api/api#add_to_cart",        as: "add_cart"
  post "/wishlist/add/:insertion",       to: "api/api#add_to_wishlist",    as: "add_wishlist"

  delete "/cart/remove/:insertion",      to: "api/api#remove_to_cart",     as: "remove_cart"
  delete "/wishlist/remove/:insertion",  to: "api/api#remove_to_wishlist", as: "remove_wishlist"
  
  # insertion routes
  get "/insertion/search",  to: "insertion#search",   as: "search_insertion"
  get "/insertion/:id",     to: "insertion#show",     as: "show_insertion"

  post "/insertion",        to: "insertion#create"
  post "/insertion/:id",    to: "insertion#edit",     as: "edit_insertion"

  delete "/insertion/:id",  to: "insertion#destroy",  as: "destroy_insertion"

  get "/meeting/new/:id", to: "meeting#new", as: "meeting"
  get "/meeting/:id", to: "meeting#show", as: "show_meeting"
  post "/meeting/accept/:id", to: "meeting#accept", as: "accept_meeting"
  post "/meeting", to: "meeting#create", as: "create_meeting"
  post "/meeting/:id", to: "meeting#update", as: "edit_meeting"
  delete "/meeting/:id", to: "meeting#destroy", as: "destroy_meeting"
  
  post "/review/create", to: "review#create", as: "create_review"

  post "questions/reply/:id", to: "questions#reply", as: "question_reply"
  post "/questions", to: "questions#create"

  post "/history/insertion/:id", to: "history#complete", as: "complete_purchase"
  
  resources :questions

  # devise routes
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
end

app/models/insertion.rb
class Insertion < ApplicationRecord
  enum :categories, {
    accessories: 0,
    beauty: 1,
    books: 2,
    eletronics: 3,
    films: 4,
    games: 5,
    healts: 6,
    musics: 7,
    photos: 8,
    sports: 9,
    videogames: 10
  },
  prefix: true

  belongs_to :seller
  has_many :question
  has_many :history

  has_one_attached :image

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }

  def seller_location
    User.find(seller_id).location
  end

  def map 
    response = HTTP.get("https://maps.googleapis.com/maps/api/staticmap?center=40.714728,-73.998672&zoom=12&size=400x400&maptype=roadmap&key=AIzaSyABJc3-uSJdVUa1YJbAua2NRnqZx3UxnlI&signature=YOUR_SIGNATURE")
    response.parse
  end 

  private

  def self.seller_name(id)
    user = User.find(Seller.find(id).user_id)
    "#{user.first_name} #{user.last_name}"
  end
end

app/controllers/insertion_controller.rb
require "opencage/geocoder"

class InsertionController < ApplicationController
  before_action :sanitize_insertion_params
  before_action :set_insertion, only: %i[show edit destroy]

  # * DONE
  def show
    @questions = Question.where(insertion_id: @insertion).limit(5)
    user = User.find(Seller.find(@insertion.seller_id).user_id)
    
    if user_signed_in?
      @cart = Cart.where(user_id: current_user)
      @seller = Seller.find_by(user_id: current_user)
      @wishlist = Wishlist.where(user_id: current_user)
    end

    geocoder = OpenCage::Geocoder.new(api_key: Rails.application.credentials.dig(:opencage_api))
    results = geocoder.geocode("#{user.address}, #{user.city}")
    gon.lat = results.first.coordinates[0]
    gon.lng = results.first.coordinates[1]
  end

  def create
    params[:insertion][:categories] = params[:insertion][:categories].to_i
    @insertion = Insertion.new(insertion_params)

    if @insertion.valid? 
        @insertion.save
        redirect_to '/profile/'+current_user.id.to_s
    else
        redirect_to '/profile/'+current_user.id.to_s, alert: "Completa tutti i campi per vendere un articolo"
    end
  end
  
  def edit
    params[:insertion][:categories] = params[:insertion][:categories].to_i
    
    respond_to do |format|
      if @insertion.update(insertion_params)
        respond_to { |format| render inline: "location.reload();" }
      else
        format.html { redirect_to user_profile_path(current_user), alert: "Completa tutti i campi per vendere un articolo" }
      end
    end
  end
  
  def destroy
    @insertion.destroy
    
    redirect_to '/profile/'+current_user.id.to_s
  end

  # * DONE
  def search
    @seller = Seller.find_by(user_id: current_user)
    
    if params[:search] != ""
      @insertions = Insertion.where("title like ?", "%#{params[:search]}%")
      
      if user_signed_in?
        @cart = Cart.where(user_id: current_user)
        @wishlist = Wishlist.where(user_id: current_user)

        @insertions = @insertions.filter { |insertion| insertion.seller_id != @seller.id } if @seller
      end
    end
  end

  private
  
  # * DONE
  def set_insertion
    @insertion = Insertion.find(params[:id])
  end
  
  # * DONE
  def sanitize_insertion_params
    params[:id] = params[:id].to_i
  end
  
  # * DONE
  def insertion_params
    params.require(:insertion).permit(:seller_id, :image, :title, :description, :price, :categories)
  end
end

app/helpers/insertion_helper.rb
module InsertionHelper
end

app/views/insertion/search.erb
<% if !@insertion %>
  <div class="text-center my-5">
  <h2 class="mb-0">La tua ricerca non ha prodotto alcun risultato</h2>
  <%= link_to root_path, class: "fw-bold" do %>Torna alla home<% end %>
  </div>
<% else %>
  <h2 class="text-center my-5">Risultati della ricerca</h2>
  <div class="row row-cols-4">
    <% @insertion.each do |ins| %>    
      <div class="col mx-auto mb-4">
        <%= render "shared/insertion", insertion: ins %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/insertion/search.html.erb
<div class="text-center mt-5">
  <div class="mb-3">
    <span class="fw-bold">Risultati della ricerca: <%= params[:search] %></span>
  </div>
  <% if !@insertions || @insertions.length == 0%>
    <div>
        <span class="fw-bold">La tua ricerca non ha prodotto alcun risultato</span>
    </div>
    <div class="mt-5">
      <%= link_to root_path, class: "fw-bold" do %>
        Torna alla home
      <% end %>
    </div>
  <% else %>
    <div class="row row-cols-4">
      <% @insertions.each do |insertion| %>    
        <div class="col mb-4">
          <%= render "shared/insertion", insertion: insertion %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/insertion/show.html.erb
<%# * DONE %>
<div class="container-fluid">
  <div class="insertion-container">
    <%# insertion information %>
    <div class="mt-3">
      <% if !Seller.find(@insertion.seller_id).active %>
        <span class="fw-bold">Venditore attualmente non attivo</span>
      <% elsif Meeting.find_by(insertion_id: @insertion) %>
        <span class="fw-bold">Attualmente prenotato</span>
      <% else %>
        <% if user_signed_in? %>
          <% if current_user.id != Seller.find(@insertion.seller_id).user_id %>            
            <%= link_to "Prenota un incontro", meeting_path(@insertion), class: "fw-bold", style: "font-size: 12px;" %>
          <% end %>
        <% else %>
          <button class="border-0 bg-transparent" data-bs-toggle="modal" data-bs-target="#sign_in">
            <span class="fw-bold" style="font-size: 12px;">Accedi per acquistare</span>
          </button>
        <% end %>
      <% end %>
      <h5 class="fw-bold mt-1 mb-0"><%= @insertion.title %></h5>
      <span><%= @insertion.description %></span>
      <%= link_to user_profile_path(Seller.find(@insertion.seller_id).user_id) do %>
        <h6 class="my-1" style="font-size: 12px;"><%= Insertion.seller_name(@insertion.seller_id) %></h6>
      <% end %>
      <%= link_to home_path(@insertion.categories) do %>
        <span class="fw-bold btn btn-sm btn-primary"><%= @insertion.categories %></span>
      <% end %>
    </div>

    <div>
      <div>
        <span class="fw-bold"><%= sprintf('%.2f', @insertion.price) %> €</span>
      </div>
      <% if user_signed_in? %>
        <div class="d-flex justify-content-center">
          <%# wishlist section %>
          <% if @wishlist&.find_by(insertion_id: @insertion) %>
            <%= button_to remove_wishlist_path(@insertion), method: :delete do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="#fe385c" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
              </svg>
            <% end %>
          <% else %>
            <%= button_to add_wishlist_path(@insertion) do %>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
              </svg>
            <% end %>
          <% end %>
          
          <%# cart section %>
          <% if @cart&.find_by(insertion_id: @insertion) %>
            <%= button_to remove_cart_path(@insertion), method: :delete, id: "remove_cart" do %>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd" />
              </svg>
            <% end %>
          <% else %>
            <%= button_to add_cart_path(@insertion), id: "add_cart" do %>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd" />
              </svg>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="text-center">
    <%# insertion image %>
    <%= image_tag(@insertion.image, class: "insertion-image") %>
  </div>

  <div class="mt-2 mb-5">
    <span class="fw-bold">Posizione del venditore</span>
    <div class="mt-2" id="map"></div>
  </div>

  <div>
    <%# answer section %>
    <div class="mb-2">
      <span class="fw-bold">Domande</span>
    </div>
    <% if @questions.count == 0 %>
      <div class="mb-4">
        <span>Nessuna domanda per l'articolo</span>
      </div>
    <% else %>
      <div class="row row-cols-4">
      <% @questions.each do |question| %>
        <div class="col mb-4">
          <div class="card">
            <div class="text-center mt-2">
              <h6 class="fw-bold mb-0">Domanda</h6>
              <span class="fw-light"><%= question.question%></span>
            </div>
            <div class="text-center mt-4">
              <h6 class="fw-bold mb-0">Risposta</h6>
              <span class="fw-light"><%= if question.reply.empty? then "-" else question.reply end %></span>
            </div>
            <% if user_signed_in? && current_user.id == Seller.find(@insertion.seller_id).user_id && question.reply == ""%>
              <%= form_with url: question_reply_path(question), class: "text-center mb-2", id: "reply_form", method: :post do |f| %>
                <%= f.text_area :reply, id: "reply", style: "resize: none; border: 1px solid #fe385c;" %>
                <%= f.submit "Rispondi", class: "border-0 bg-transparent fw-bold", style: "font-size: 12px;" %>
              <% end %>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    <% end %>

    <%# question section %>
    <% if user_signed_in? && @insertion.seller_id != @seller&.id %>
      <div>
        <div class="mb-2">
          <span class="fw-bold">Fai una domanda</span>
        </div>      
        <div class="d-flex justify-content-center align-items-center mb-2">  
          <%= form_for(:question, url: questions_path, class: "question-form", id: "question_form") do |form| %>
            <%= form.hidden_field :user_id, value: current_user.id %>
            <%= form.hidden_field :insertion_id, value: @insertion.id %>
            <%= form.text_area :question, class: "form-control", id: "question_area"%>
            <div class="mt-2">
              <%= form.submit "Invia", class: "modal-btn" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
  function initMap() {
    const coordinates = { lat: gon.lat, lng: gon.lng };

    const map = new google.maps.Map(
      document.getElementById("map"), { 
        center: coordinates, 
        zoom: 12
    });

    const marker = new google.maps.Marker({ position: coordinates, map, title: "Seller position" });
  }
</script>  