config/routes.rb
Rails.application.routes.draw do
  # root path
  root "home#index"

  # home routes
  get "/home/index",         to: "home#index"
  get "/category/:category", to: "home#index", as: "home"

  # user routes
  get "cart/:id",           to: "user#cart",      as: "user_cart"
  get "history/:id",        to: "user#history",   as: "user_history"
  get "user/insertion/:id", to: "user#insertion", as: "user_insertion"
  get "profile/:id",        to: "user#profile",   as: "user_profile"
  get "wishlist/:id",       to: "user#wishlist",  as: "user_wishlist"

  # user API routes
  post "/update_user/:id",               to: "api/api#user_to_seller",     as: "update_user"
  post "/restore_user/:id",              to: "api/api#seller_to_user",     as: "restore_user"

  post "/cart/add/:insertion",           to: "api/api#add_to_cart",        as: "add_cart"
  post "/wishlist/add/:insertion",       to: "api/api#add_to_wishlist",    as: "add_wishlist"

  delete "/cart/remove/:insertion",      to: "api/api#remove_to_cart",     as: "remove_cart"
  delete "/wishlist/remove/:insertion",  to: "api/api#remove_to_wishlist", as: "remove_wishlist"
  
  # insertion routes
  get "/insertion/search",  to: "insertion#search",   as: "search_insertion"
  get "/insertion/:id",     to: "insertion#show",     as: "show_insertion"

  post "/insertion",        to: "insertion#create"
  post "/insertion/:id",    to: "insertion#edit",     as: "edit_insertion"

  delete "/insertion/:id",  to: "insertion#destroy",  as: "destroy_insertion"

  get "/meeting/new/:id", to: "meeting#new", as: "meeting"
  get "/meeting/:id", to: "meeting#show", as: "show_meeting"
  post "/meeting/accept/:id", to: "meeting#accept", as: "accept_meeting"
  post "/meeting", to: "meeting#create", as: "create_meeting"
  post "/meeting/:id", to: "meeting#update", as: "edit_meeting"
  delete "/meeting/:id", to: "meeting#destroy", as: "destroy_meeting"
  
  post "/review/create", to: "review#create", as: "create_review"

  post "questions/reply/:id", to: "questions#reply", as: "question_reply"
  post "/questions", to: "questions#create"

  post "/history/insertion/:id", to: "history#complete", as: "complete_purchase"
  
  resources :questions

  # devise routes
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :insertion
  belongs_to :seller
  belongs_to :user

  validates :date, presence: true
  validates :place, presence: true
end

app/controllers/meeting_controller.rb
require "google/apis/calendar_v3"
require "opencage/geocoder"

class MeetingController < ApplicationController
  before_action :set_meeting, only: %i[accept destroy update]

  def new
    @insertion = Insertion.find(params[:id])
    @seller = Seller.find(@insertion.seller_id)
    @user = User.find(@seller.user_id)

    geocoder = OpenCage::Geocoder.new(api_key: Rails.application.credentials.dig(:opencage_api))
    results = geocoder.geocode("#{@user.address}, #{@user.city}")
    gon.lat = results.first.coordinates[0]
    gon.lng = results.first.coordinates[1]
  end

  def accept
    # update or create Google Calendar event if user is logged with Google Account
    if current_user.provider == "google_oauth2"      
      service = Google::Apis::CalendarV3::CalendarService.new
      service.authorization = session[:access_token]
      event = Google::Apis::CalendarV3::Event.new(
        summary: Insertion.find(@meeting.insertion_id).title,
        location: @meeting.place,
        description: Insertion.find(@meeting.insertion_id).description,
        start: Google::Apis::CalendarV3::EventDateTime.new(
          date_time: @meeting.date.to_datetime,
          time_zone: "Europe/Rome"
        ),
      end: Google::Apis::CalendarV3::EventDateTime.new(
          date_time: @meeting.date.to_datetime,
          time_zone: "Europe/Rome"
        ),
        attendees: [
          Google::Apis::CalendarV3::EventAttendee.new(
            email: User.find(@meeting.user_id).email
          ),
          Google::Apis::CalendarV3::EventAttendee.new(
            email: User.find(Seller.find(@meeting.seller_id).user_id).email
          )
        ],
      )
      
      if @meeting.calendar_id == ""
        event_created = service.insert_event("primary", event)    
        @meeting.calendar_id = event_created.id
      else
        service.update_event("primary", @meeting.calendar_id, event)
      end
    end

    if ActiveModel::Type::Boolean.new.cast(params[:owner])
      @meeting.update_attribute(:seller_approvation, true)
    else
      @meeting.update_attribute(:user_approvation, true)
    end

    redirect_to '/meeting/'+@meeting.insertion_id.to_s
  end
  
  def create
    @meeting = Meeting.new(meeting_params)

    geocoder = OpenCage::Geocoder.new(api_key: Rails.application.credentials.dig(:opencage_api))
    results = geocoder.geocode(@meeting.place) if @meeting.place != ""
    
    # create Google Calendar event if user is logged with Google Account
    if results && results.length > 0 && current_user.provider == "google_oauth2"
      event = Google::Apis::CalendarV3::Event.new(
        summary: Insertion.find(@meeting.insertion_id).title,
        location: @meeting.place,
        description: Insertion.find(@meeting.insertion_id).description,
        start: Google::Apis::CalendarV3::EventDateTime.new(
          date_time: @meeting.date.to_datetime,
          time_zone: "Europe/Rome"
        ),
        end: Google::Apis::CalendarV3::EventDateTime.new(
          date_time: @meeting.date.to_datetime,
          time_zone: "Europe/Rome"
        ),
        attendees: [
          Google::Apis::CalendarV3::EventAttendee.new(
            email: User.find(@meeting.user_id).email
          ),
          Google::Apis::CalendarV3::EventAttendee.new(
            email: User.find(Seller.find(@meeting.seller_id).user_id).email
          )
        ],
      )

      service = Google::Apis::CalendarV3::CalendarService.new
      service.authorization = session[:access_token]

      event_created = service.insert_event("primary", event)    
      @meeting.calendar_id = event_created.id
    end

    respond_to do |format| 
      if @meeting.save
        format.html { redirect_to show_meeting_path(current_user) }
      else
        format.html { redirect_to insertion_path(@meeting.insertion_id), alert: "Errore nella prenotazione, campi non validi" }
      end
    end
  end

  def destroy
    if current_user.provider == "google_oauth2"
      service = Google::Apis::CalendarV3::CalendarService.new
      service.authorization = session[:access_token]
      
      if @meeting.calendar_id != "" && service.get_event("primary", @meeting.calendar_id).status != "cancelled"
        service.delete_event("primary", @meeting.calendar_id)
      end
    end

    @meeting.destroy
    respond_to { |format| format.js { render inline: "location.reload();" } }
  end

  def show
    redirect_to root_path if !user_signed_in? || current_user.id != params[:id].to_i

    @seller = Seller.find_by(user_id: current_user)
    @geocoder = OpenCage::Geocoder.new(api_key: Rails.application.credentials.dig(:opencage_api))
    @meetings = Meeting.where(user_id: params[:id])
    
    if Seller.find_by(user_id: params[:id]) && @meetings.length == 0
      @meetings = Meeting.where(seller_id: Seller.find_by(user_id: params[:id]).id)
    end
  end

  def update
    # @meeting.update_attribute(:date, params[:meeting][:date])
    # @meeting.update_attribute(:place, params[:meeting][:place])

    if ActiveModel::Type::Boolean.new.cast(params[:meeting][:owner])
      @meeting.update_attribute(:user_approvation, false)
      @meeting.update_attribute(:seller_approvation, true)
    else
      @meeting.update_attribute(:user_approvation, true)
      @meeting.update_attribute(:seller_approvation, false)
    end

    if @meeting.update(meeting_params)
      service = Google::Apis::CalendarV3::CalendarService.new
      service.authorization = session[:access_token]

      if current_user.provider == "google_oauth2" && service.get_event("primary", @meeting.calendar_id).status != "cancelled"    
        event = Google::Apis::CalendarV3::Event.new(
          summary: Insertion.find(@meeting.insertion_id).title,
          location: @meeting.place,
          description: Insertion.find(@meeting.insertion_id).description,
          start: Google::Apis::CalendarV3::EventDateTime.new(
            date_time: @meeting.date.to_datetime,
            time_zone: "Europe/Rome"
          ),
          end: Google::Apis::CalendarV3::EventDateTime.new(
              date_time: @meeting.date.to_datetime,
              time_zone: "Europe/Rome"
          ),
          attendees: [
              Google::Apis::CalendarV3::EventAttendee.new(
                email: User.find(@meeting.user_id).email
              ),
              Google::Apis::CalendarV3::EventAttendee.new(
                email: User.find(Seller.find(@meeting.seller_id).user_id).email
              )
            ],
          )
          
          if @meeting.calendar_id == ""
            event_created = service.insert_event("primary", event)    
            @meeting.calendar_id = event_created.id
          else
            service.update_event("primary", @meeting.calendar_id, event)
          end

        redirect_to '/meeting/'+params[:id].to_s
      else
        redirect_to show_meeting_path(params[:id]), alert: "Errore nella modifica della prenotazione" 
      end
    end
  end

  private

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:user_id, :seller_id, :insertion_id, :date, :place)
  end
end

app/helpers/meeting_helper.rb
module MeetingHelper
end

app/views/meeting/new.html.erb
<div class="d-flex flex-column align-items-center justify-content-center my-4">
  <h5 class="modal-title fw-bold mx-auto">Organizza un meeting</h5>
  <span>Prenota</span>
</div>

<h6 class="text-center mb-3">Indirizzo selezionato: <span id="selected_address"><%= @user.address %>, <%= @user.city %></span></h6>
<%= form_for(:meeting, url: create_meeting_path, class: "mb-3", id:"meeting_form") do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :seller_id, value: @seller.id %>
  <%= f.hidden_field :insertion_id, value: @insertion.id %>
  <div class="row mb-3">
    <div class="col-6 my-auto">
      <%= f.datetime_local_field :date, class: "form-control", id:"date", min: Time.now.strftime('%Y-%m-%d') %>
    </div>
    <div class="col-6">
      <div class="form-floating">
        <%= f.text_field :place, class: "form-control", placeholder: "Address" %>
        <%= f.label :place %>
      </div>
    </div>
  </div>
  <div class="text-center">
    <%= f.submit "Prenota", class: "modal-btn", style: "width: 100px;" %>
  </div>
<% end %>

<div id="map"></div>

<script>
  function initMap() {
    const coordinates = { lat: gon.lat, lng: gon.lng };

    const map = new google.maps.Map(
      document.getElementById("map"), { 
        center: coordinates, 
        zoom: 12
    });

    const marker = new google.maps.Marker({ position: coordinates, map, title: "Seller position" });

    const address = document.getElementById("selected_address");
    const input_field = document.getElementById("meeting_place");

    input_field.addEventListener("change", (event) => {
      address.innerHTML = event.target.value

      const URL = `https://api.opencagedata.com/geocode/v1/json?q=${encodeURI(event.target.value)}&key=<%= Rails.application.credentials.dig(:opencage_api) %>`;

      fetch(URL)
        .then(res => res.json())
        .then(res => {
          const coordinates = res.results[0].geometry
          const marker = new google.maps.Marker({ position: coordinates, map, title: "Meeting position" });
          map.setCenter(marker.getPosition())
          console.log(marker.getPosition());
        })
        .catch(err => console.error(err))

    });
  }

</script>  

app/views/meeting/show.html.erb
<div class="my-3">
  <span class="fw-bold">Prenotazioni</span>
    <% if @meetings.length == 0 %>
    <h6 class="mt-3">Nessun elemento</h6>
  <% end %>
</div>
<% @meetings.each do |meeting| %>
  <div class="d-flex align-items-center justify-content-between">
    <%# meeting information %>
    <div class="d-inline-flex align-items-center">
      <%= link_to show_insertion_path(meeting.insertion_id) do %>
        <%= render "shared/insertion", insertion: Insertion.find(meeting.insertion_id) %>
      <% end %>
      <div class="ms-5">
        <div>
          <h6 class="fw-bold mb-1"><%= meeting.date %></h6>
          <span class="fw-bold"><%= meeting.place %></span>
        </div>
        <div class="mt-2">
          <span class="btn btn-sm <%= if meeting.user_approvation then "btn-success" else "btn-danger" end %>">Utente</span>
          <span class="btn btn-sm <%= if meeting.seller_approvation then "btn-success" else "btn-danger" end %>">Venditore</span>
        </div>
      </div>
    </div>

    <div class="d-inline-flex align-items-center flex-column">
      <%# meeting position %>
      <div id="map" style="height: 250px; width: 500px;"></div>
      <%# meeting features %>
      <div class="d-inline-flex mt-2">
        <% if (current_user.id == meeting.user_id && !meeting.user_approvation) || (current_user.id == Seller.find(meeting.seller_id).user_id && !meeting.seller_approvation) %>            
          <%= form_with url: accept_meeting_path(meeting.id), method: :post do |f| %>
            <%= f.hidden_field :owner?, value: meeting.insertion.seller_id == Seller.find_by(user_id: current_user).id if Seller.find_by(user_id: current_user) %>
            <%= f.hidden_field :user, value: current_user.id %>
            <%= f.submit "Accetta", class: "btn btn-sm btn-success mx-1" %>
          <% end %>
        <% end %>
        <button class="border-0 bg-transparent" data-bs-toggle="modal" data-bs-target="#edit_meeting">
          <span class="text-white btn btn-sm btn-warning mx-1">Modifica</span>
        </button>
        <%= button_to destroy_meeting_path(meeting.id), class: "text-white btn btn-sm btn-danger mx-1", method: :delete do %>
          Elimina
        <% end %>
        <% if Seller.find_by(user_id: current_user) && meeting.seller_id == Seller.find_by(user_id: current_user).id %>
          <%= form_with url: complete_purchase_path(meeting.id), method: :post do |f| %>
            <%= f.hidden_field :insertion, value: meeting.insertion_id %>
            <%= f.hidden_field :seller, value: meeting.seller_id %>
            <%= f.hidden_field :user, value: meeting.user_id %>
            <%= f.hidden_field :date, value: meeting.date %>
            <%= f.hidden_field :place, value: meeting.place %>
            <%= f.submit "Concludi", class: "btn btn-sm btn-secondary mx-1" %>
          <% end %>
        <% end %>
      </div>
    </div>
    
    <%= render "shared/modal/edit_meeting", meeting: meeting %>
  </div>
  <hr class="mt-3"/>

  <% results = @geocoder.geocode(meeting.place) %>
  <script>
    function initMap() {
        const coordinates = { lat: <%= results.first.coordinates[0] %>, lng: <%= results.first.coordinates[1] %> };
        const map = new google.maps.Map(
          document.getElementById("map"), { 
            center: coordinates, 
            zoom: 12
        });

        new google.maps.Marker({ position: coordinates, map, title: "Seller position" });
    }
  </script>
<% end %>